name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build NestJS app
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and restart application
        run: |
          # Copy the dist folder to the VPS
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key" \
            dist/ \
            ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.DEPLOY_PATH }}/dist/

          # Setup environment variables and restart the app with PM2
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }} "\
            export NVM_DIR=\$HOME/.nvm && \
            source \$NVM_DIR/nvm.sh && \
            nvm use default && \
            echo '${{ secrets.PRODUCTION_ENV }}' > ${{ secrets.DEPLOY_PATH }}/dist/.env && \
            cd ${{ secrets.DEPLOY_PATH }}/dist && \
            pm2 delete dz_artisan_server || true && \
            pm2 start main.js --name dz_artisan_server \
          "
